// Traducción inicial de la interfaz. Las claves que aún no tienen traducción
// delegan en el banco inglés para que cambiar de idioma nunca deje una pantalla
// sin texto. La crónica se traducirá por familias, sin cambiar las claves
// guardadas en las partidas.

export const UI_BANK_ES: Record<string, string> = {
  'app.valley': 'El valle',
  // M-0 · las existencias nuevas, la cara del ánimo y la oferta del camino.
  'app.vitals.stone': '{count} de piedra',
  'app.vitals.silver': '{count} de plata',
  'app.vitals.spirits': 'La aldea está {mood}',
  'mood.low': 'hundida',
  'mood.grim': 'seria',
  'mood.calm': 'tranquila',
  'mood.glad': 'contenta',
  'offer.pedlar.say': 'Un buhonero quiere {wood} de leña por {silver} de plata.',
  'offer.factor_visit.say': 'Un tratante de grano ofrece {silver} de plata por {grain} fanegas.',
  'offer.drover_visit.say': 'Un ganadero vende una vaca por {silver} de plata.',
  'offer.salt_visit.say': 'Un salinero vende sal por {silver} de plata.',
  'offer.take': 'Aceptar',
  'offer.leave': 'Dejarlo ir',
  'offer.cannot': 'La aldea no puede pagarlo.',
  'app.close': 'Cerrar',
  'app.orders': 'Órdenes permanentes',
  'app.orders.now': 'Siembra {sowing} · manos a {hands} · construir {build}',
  'app.orders.open': 'Cambiar las órdenes permanentes',
  'app.speed.open': 'Cambiar la velocidad',
  'app.sowing': 'Siembra',
  'app.sowing.lean': 'Escasa',
  'app.sowing.enough': 'Suficiente',
  'app.sowing.heavy': 'Abundante',
  'app.hands': 'Manos libres',
  'app.hands.works': 'Construcción',
  'app.hands.both': 'Ambas',
  'app.hands.wood': 'Madera',
  'app.build': 'Construir primero',
  'app.build.none': 'Según necesidad',
  'app.build.food': 'Alimento',
  'app.build.shelter': 'Tejados',
  'app.build.craft': 'Oficios',
  'app.build.faith': 'Fe',
  'app.build.defence': 'Murallas',
  'app.year': 'AÑO {year}',
  'app.clock.time': '{hour}:00',
  'app.clock.date': 'Año {year} · {season}, día {day}',
  'app.speed.controls': 'Velocidad de simulación',
  'app.speed.pause': 'Pausar',
  'app.speed.resume': 'Continuar',
  'app.speed.multiplier': '{speed}×',
  'founding.label': 'El valle está habitado',
  'milestone.kind.first_of_kind': 'El primero de su clase',
  'milestone.kind.peak_people': 'Nunca hubo tantos',
  'milestone.kind.turn_of_decade': 'Un cambio de década',
  'milestone.kind.work_done': 'El trabajo ha terminado',
  'nav.bar': 'Dónde mirar',
  'nav.valley': 'Valle',
  'nav.chronicle': 'Crónica',
  'nav.people': 'Personas',
  'app.sheet': 'Detalles',
  'app.vitals': 'El valle de un vistazo',
  'app.vitals.people': '{count} aldeanos',
  'app.vitals.food': 'Comida para {weeks} semanas',
  'app.vitals.wood': '{count} de madera',
  'app.vitals.morale': 'Ánimo {value} de 100',
  'app.season.spring': 'Primavera',
  'app.season.summer': 'Verano',
  'app.season.autumn': 'Otoño',
  'app.season.winter': 'Invierno',
  'app.sound.on': 'Sonido activado',
  'app.sound.off': 'Sonido desactivado',
  'title.name': 'El valle',
  'title.tagline': 'Dos personas llegan por la sierra con una cesta de gallinas y un saco de grano. Lo que los años hagan con ellos no depende sólo de ellos.',
  'title.continue': 'Continuar',
  'title.continue.detail': 'Año {year} · {count} con vida',
  'title.new': 'Fundar un valle nuevo',
  'title.seed': 'Número del valle',
  'title.seed.hint': 'El mismo número da a cualquiera el mismo valle inicial. Nadie lo conduce de la misma manera.',
  'title.reroll': 'Otro',
  'title.new.working': 'Fundando…',
  'title.dev': 'Desarrollo',
  'title.dev.year': 'Abrir en el año',
  'title.dev.hint': 'El valle avanza con la política de referencia antes de abrirse. Lo que ves es una partida real.',
  'language.label': 'Idioma',
  'language.english': 'English',
  'language.spanish': 'Español',
  'intro.orders': 'La línea inferior contiene las órdenes permanentes: qué sembrar, dónde van las manos y qué levantar. Toca para cambiarlas.',
  'intro.time': 'El botón de la derecha marca el ritmo. El valle sigue solo; vuelve cuando quieras.',
  'crossroad.waiting': 'Hay una decisión pendiente',
  'crossroad.pending_pill': 'Una decisión espera',
  'welcome.title': 'Mientras no estabas',
  'epitaph.title': 'El valle está vacío',
  'epitaph.extinction': 'El último murió en el año {year}.',
  'epitaph.abandoned': 'Las últimas familias se marcharon en el año {year}.',
  'epitaph.dispersed': 'La aldea se deshizo en el año {year}.',
  'epitaph.summary': '{years} años. {peak} personas en su momento de mayor tamaño.',
  'epitaph.chronicle': 'Leer la crónica',
  'epitaph.begin': 'Empezar de nuevo',
  'chronicle.source': 'Crónica del valle',
  'chronicle.current': 'Este valle',
  'chronicle.archived': 'Valle anterior {number} — {years} años, máximo {peak}',
  'inspect.raised': 'Construido en el año {year}.',
  'inspect.granary': '{grain} de grano de {capacity} de capacidad.',
  'inspect.house': '{people} personas bajo este techo.',
  'inspect.house.named': '{people} personas bajo este techo: {names}.',
  'inspect.role.empty': 'Aquí no trabaja ningún {role}.',
  'inspect.role.holder': '{name} trabaja aquí como {role}.',
  'inspect.villager': 'Aldeano {id}',
  'inspect.opinion.trusts': 'Confía en {name}: {value}.',
  'inspect.opinion.resents': 'Resiente a {name}: {value}.',
  'inspect.memory': '{memory} — año {year}.',
  'inspect.age': '{age} inviernos.',
  'inspect.age.short': '{age} inviernos',
  'inspect.traits.none': 'Sin rasgos conocidos.',
  'inspect.today': 'Hoy: {doing}',
  'inspect.doing.bundle': 'llevando madera',
  'inspect.doing.stone': 'llevando piedra',
  'inspect.doing.grain': 'llevando grano',
  'inspect.doing.home': 'en casa',
  'inspect.doing.leaving': 'saliendo',
  'inspect.doing.walking': 'por los caminos',
  'inspect.doing.working': 'trabajando',
  'inspect.doing.returning': 'de camino a casa',
  'inspect.doing.resting': 'descansando',
  'kin.mother': 'madre',
  'kin.father': 'padre',
  'kin.son': 'hijo',
  'kin.daughter': 'hija',
  'kin.friend': 'amigo',
  'kin.rival': 'rival',
  'inspect.story': 'Historia de vida',
  'inspect.story.close': 'Cerrar la historia',
  'inspect.gone': 'Ausente',
  'inspect.terrain.people': '{people} personas viven en el valle.',
  'inspect.died': 'Murió en el año {year}, con {age} inviernos.',
  'inspect.left': 'Abandonó el valle en el año {year}.',
  'inspect.follow': 'Seguir',
  'inspect.unfollow': 'Dejar de seguir',
  'inspect.track.note': 'Rodea a {name} en el mapa y mantiene la vista sobre él.',
  'people.empty': 'Todavía nadie tiene nombre en el valle.',
  'people.back': 'Volver a la lista',
  'people.scope': '{named} con nombre de {population} habitantes',
  'role.leader': 'jefe',
  'role.smith': 'herrero',
  'role.midwife': 'comadrona',
  'role.priest': 'cura',
  'role.woodward': 'guardabosques',
  'role.reeve': 'alguacil',
  'role.herbalist': 'herbolario',
  'role.stranger': 'forastero',
  'terrain.meadow': 'pradera',
  'terrain.forest': 'bosque',
  'terrain.water': 'agua',
  'terrain.rock': 'roca',
  'terrain.marsh': 'marisma',
  'terrain.cleared': 'claro',
  'terrain.land': 'tierra',
  'building.house': 'casa',
  'building.field': 'campo',
  'building.granary': 'granero',
  'building.chapel': 'capilla',
  'building.smithy': 'herrería',
  'building.well': 'pozo',
  'building.mill': 'molino',
  'building.palisade': 'empalizada',
  'building.wall': 'muralla',
  'building.church': 'iglesia',
  'building.stone_house': 'casa de piedra',
  'building.watchtower': 'torre de vigilancia',
  'building.grave_yard': 'cementerio',
  'trait.ambitious': 'ambicioso',
  'trait.devout': 'devoto',
  'trait.spiteful': 'rencoroso',
  'trait.craven': 'cobarde',
  'trait.generous': 'generoso',
  'trait.stubborn': 'tozudo',
  'trait.cunning': 'astuto',
  'trait.kind': 'amable',
  'trait.hot_tempered': 'irascible',
  'trait.frail': 'frágil',
  'trait.hardy': 'resistente',
  'trait.greedy': 'avaricioso',
  'trait.loyal': 'leal',
  'trait.proud': 'orgulloso',
  'trait.secretive': 'reservado',
  'memory.lost_child': 'perdió un hijo',
  'memory.was_blamed': 'fue culpado',
  'memory.was_saved': 'fue salvado',
  'memory.was_passed_over': 'fue ignorado',
  'memory.went_hungry': 'pasó hambre',
  'memory.lost_home': 'perdió su casa',
  'memory.stole': 'robó',
  'memory.unspoken': 'no dicho',
};
